### ISSUE TITLE
When is this assignment due?

### ISSUE THREAD

**Issue by Ycasas-Jan** [StockTickerAgent/PHP-CodeIgniter.StockTickerAgent#10]
@jim-parry In the document it says the assignment is due in 10 days. We have our lab on wednesday feburary 3 and our assignment should be due on saturday feburary 13 but on D2L it said the assignment was due on friday feburary 12.

**Comment by jim-parry** [comment]
You have a point - Feb 12 gives 10 days but only 9 nights. I will adjust the due date on D2L and post a news item on D2L.

ps - Your point/question is not repo or code-based, and would be more appropriate as a normal email, rather than an issue :-/
